name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Modify this to match your branch name

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    env:
      DECODED_USERNAME: ${{ secrets.DECODED_USERNAME }}  # Assuming you have a secret named DECODED_USERNAME

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files and directories
        run: ls -R

      - name: Set Decoded Username
        run: echo "Decoding username" && echo $DECODED_USERNAME
        env:
          DECODED_USERNAME: ${{ secrets.DECODED_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t $DECODED_USERNAME/sample:v1 ./sample-service/.

      - name: Push Docker image to Docker Hub
        run: docker push $DECODED_USERNAME/sample:v1
